name: Apps CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f modules/requirements.txt ]; then pip install -r requirements.txt; fi

      # Add this step to run build.sh
      - name: Run build script
        run: |
          chmod +x ./tests/build-for-test.sh
          ./tests/build-for-test.sh

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        env:
          LOGIN_EMAIL: ${{secrets.LOGIN_EMAIL}}
          LOGIN_EMAIL_PASSWORD: ${{secrets.LOGIN_EMAIL_PASSWORD}}
        run: |
          pytest
